### ISSUE TITLE
No "CmakeList.txt" under build folder

### ISSUE THREAD

**Issue by DLyons** [openglsuperbible/sb7code#10]
When following this step of the build instructions:

> Open a command prompt and change to the build directory in the source archive.
> Type:
>    cmake -G "Visual Studio 12" .

The following error is thrown;

> Make Error: The source directory "D:/Projects/sb7code/build" does not appear to contain CMakeLists.txt.

Despite there being a file named 

> !RUN CMAKE FROM HERE.txt

However running it from the root directory works.

**Comment by jslee02** [comment]
Why did you add `"""` right after `..`? It should work without `"""`. If you intended to add cmake options then you should at least put a space between `..` and the options like `cmake -G "Visual Studio 12" .. -DSOME_OPTION=VALUE`.

**Comment by DLyons** [comment]
Triple quotes were a typo.

**Comment by jslee02** [comment]
Please try with this command:

```
cmake -G "Visual Studio 12" ..
```

You should use `..` instead of `.`.

**Comment by DLyons** [comment]
Ahh well spotted, my mistake entirely.

**Comment by PhilParisot** [comment]
do the periods make any difference?
