### ISSUE TITLE
Will the media files get their own repository?

### ISSUE THREAD

**Issue by georgeraraujo** [openglsuperbible/sb7code#4]
I would like to create a pull request for some shaders I tweaked, and also ask that `media/textures/salad-gray.ktx` is uploaded - it's not available in the .ZIP as of today (July 24th), and it is needed in line 90 of `src/prefixsum2d/prefixsum2d.cpp`.

**Comment by grahamsellers** [comment]
Git doesn't play well with big binaries, so I won't put them under revision control.

I've added salad-gray.ktx to the media archive and uploaded it to openglsuperbible.com. I'll take a look at moving the shaders into the main git repository.

**Comment by georgeraraujo** [comment]
> Git doesn't play well with big binaries, so I won't put them under revision control.
> 
> I've added salad-gray.ktx to the media archive and uploaded it to openglsuperbible.com. I'll take a look at moving the shaders into the main git repository.

I understand. Thanks!
