### ISSUE TITLE
Installation in Windows 10 Visual Studio 2019

### ISSUE THREAD

**Issue by JuanjoTorres** [openglsuperbible/sb7code#43]
Windows / Microsoft Visual Studio 2019
--------------------------------------

I leave here the configuration of the installation of Visual Studio 2019 in Windows. Before modifying anything I got an error with the GLFW compiled libraries. The solution (or at least as it has worked for me) was changing the environment and assigning the platform on which the programs will run. 
I have also fixed the output of the last cmake command where files were not being generated where they should be. **This onstallation guide is the same as in the source code, only the essential parts are modified.**

Install CMake. Windows binaries are available from http://www.cmake.org/.
Ensure that CMake is in your path.
Open a command prompt and change to the directory where you've checked out the code.

### Build GLFW

If you are going to use the copy of GLFW included in the archive, enter the
GLFW directory in `extern/glfw-3.0.4`, and type:

    cmake -G "Visual Studio 16 2019" -A Win32 .

Open the resulting GLFW.sln file in Visual Studio and build both the debug and release configurations.

Copy and rename the resulting glfw3 libraries:

* Copy `glfw-3.0.4/src/Debug/glfw3.lib` into the `lib` directory and **rename it to glfw3_d.lib**.
* Copy `glf3-3.0.4/src/Release/glfw3.lib` into the `lib` directory but don't rename it.

### Build the samples

Open a command prompt and change to the build directory in the source archive.
Type:

    cmake -G "Visual Studio 16 2019" -A Win32 -S .. -B .

Open the resulting superbible7.sln project in Visual Studio.

The examples will build into the `bin` directory.

I hope it works for you.
Good luck!

**Comment by kylevondra** [comment]
This saved me so much trouble, thank you for this solution!

**Comment by nadal12** [comment]
Thank you so much @JuanjoTorres . Thanks to this post I was able to pass my computer graphics subject! I wish you the best.

**Comment by manuelpagliuca** [comment]
We got an hero right there... thank you so much dude.

I tried building for x64 systems and seems working the command that i used for cmake :

For building the glfw dir 
`cmake -G "Visual Studio 16 2019" -A x64 .`

for building the sb7code dir
`cmake -G "Visual Studio 16 2019" -A x64 -S .. -B .`

Have a nice day 👍

**Comment by zmertens** [comment]
I needed to copy `glfw3.dll` into the _"sb7code-master/bin"_ directory along with running the commands and building which has already been mentioned.
