### ISSUE TITLE
Chapter info in samples

### ISSUE THREAD

**Issue by jesta88** [openglsuperbible/sb7code#6]
It would be very helpful to have the chapter number as a prefix to the sample folders.

**Comment by CRTX** [comment]
Don't bother, the author doesn't seem to ever reply. Such a shame.

**Comment by CFoltin** [comment]
I totally agree. Currently, I grep for parts of the book's listing to find the right one. That can't be the intended way.

**Comment by grahamsellers** [comment]
Quoting from the book, last bullet of "How to Build the Samples", page 6:
- There is not necessarily a one-to-one mapping of listings in the book’s text and sample applications in the web package. Some sample applications demonstrate more than one concept, some aren’t mentioned in the book at all and some listings in the book don’t have an equivalent sample application.

The samples don't match up with the book directly. Where possible, I note in the book which sample goes with the description. This is the intended way.

**Comment by CFoltin** [comment]
You disappointed me. Is that too much expectation to want to see a relation between book and code? A simple comment at the top of each file like // discussed in Chapter x.y and z.w would be more helpful than your comment.

**Comment by jesta88** [comment]
If you don't have time to update this repo just say so. Simple comments as @CFoltin said would be very useful.

**Comment by grahamsellers** [comment]
I may apply some updates to the repo. I do have some outstanding pull requests which I acknowledge are somewhat old. The request was to "have the chapter number as a prefix to the sample folders" which clearly isn't going to work as some samples demonstrate topics from multiple chapters and some samples don't fit clearly into any. @CFoltin's request is reasonable although time consuming - there are something like 80 samples in the repository. A pull request that added such comments would be welcome.
